name: Build and Deploy via SSH

# 触发条件：当代码推送到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Node.js 环境
      # 使用 Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install

      # Step 4: 构建项目
      - name: Build project
        run: npm run build

      - name: Verify dist folder
        run: ls -la ./dist

      # Step 5: 部署到服务器
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: dist/
          target: /www/wwwroot/n.0122.vip
